#ifndef CONTROLLER_MAPPING_H_INCLUDE
#define CONTROLLER_MAPPING_H_INCLUDE

enum Button
{
  BUTTON_PLAYPAUSE = 0x41,
  BUTTON_POWER = 0x40,

  BUTTON_BRIGHTNESS_INC = 0x5C,
  BUTTON_BRIGHTNESS_DEC = 0x5D,

  BUTTON_RED = 0x58,
  BUTTON_GREEN = 0x59,
  BUTTON_BLUE = 0x45,
  BUTTON_WHITE = 0x44,

  BUTTON_DARK_ORANGE = 0x54,
  BUTTON_LIME = 0x55,
  BUTTON_LIGHT_BLUE = 0x49,
  BUTTON_PINK_A = 0x48,

  BUTTON_ORANGE = 0x50,
  BUTTON_TURQUIOSE = 0x51,
  BUTTON_MAUVE = 0x4D,
  BUTTON_PINK_B = 0x4C,

  BUTTON_LIGHT_ORANGE = 0x1C,
  BUTTON_TEAL = 0x1D,
  BUTTON_PURPLE = 0x1E,
  BUTTON_BLUE_A = 0x1F,

  BUTTON_YELLOW = 0x18,
  BUTTON_DARK_GREEN = 0x19,
  BUTTON_PINK = 0x1A,
  BUTTON_BLUE_B = 0x1B,

  BUTTON_RED_UP = 0x14,
  BUTTON_GREEN_UP = 0x15,
  BUTTON_BLUE_UP = 0x16,
  BUTTON_RED_DOWN = 0x10,
  BUTTON_GREEN_DOWN = 0x11,
  BUTTON_BLUE_DOWN = 0x12,
  BUTTON_DIY_ONE = 0x0C,
  BUTTON_DIY_TWO = 0x0D,
  BUTTON_DIY_THREE = 0x0E,
  BUTTON_DIY_FOUR = 0x08,
  BUTTON_DIY_FIVE = 0x09,
  BUTTON_DIY_SIX = 0x0A,

  BUTTON_QUICK = 0x17,
  BUTTON_SLOW = 0x13,

  BUTTON_AUTO = 0x0F,
  BUTTON_FLASH = 0x0B,
  BUTTON_JUMP_THREE = 0x04,
  BUTTON_JUMP_SEVEN = 0x05,
  BUTTON_FADE_THREE = 0x06,
  BUTTON_FADE_SEVEN = 0x07,
};

static uint8_t diy(const uint32_t id)
{
  switch (id)
  {
    case BUTTON_DIY_ONE:
      return 0;
    case BUTTON_DIY_TWO:
      return 1;
    case BUTTON_DIY_THREE:
      return 2;
    case BUTTON_DIY_FOUR:
      return 3;
    case BUTTON_DIY_FIVE:
      return 4;
    case BUTTON_DIY_SIX:
      return 5;
    default:
      return 6;
  }
}

#endif
